name: Release Binaries

on:
  release:
    types: [published]

permissions:
  contents: write  # Required for uploading release assets

jobs:
  build:
    name: Build binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            ext: ""
            name: linux-x86_64

          - os: macos-latest
            target: x86_64-apple-darwin
            ext: ""
            name: macos-x86_64

          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"
            name: windows-x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      
      - name: Install JSCoreGTK 4.0
        run: sudo apt-get install -y libjavascriptcoregtk-4.0-dev

      - name: Install system dependencies for Tauri
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libayatana-appindicator3-dev \
            libsoup-3.0-dev \
            build-essential \
            curl \
            pkg-config \
            libssl-dev

      - name: Build release binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        shell: bash
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/aether-renderer-gui${{ matrix.ext }} \
            dist/aether-renderer-gui-${{ github.ref_name }}-${{ matrix.name }}${{ matrix.ext }}


      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
